package DLTL.intentions;

/*Generated by MPS */

import java.awt.Toolkit;
import java.awt.datatransfer.DataFlavor;

public final class Utils {
  public static String getClipboardContent() {
    try {
      return (String) Toolkit.getDefaultToolkit().getSystemClipboard().getData(DataFlavor.stringFlavor);
    } catch (Exception e) {
      return null;
    }
  }
}
