package DLTL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_Argument;
  private ConceptPresentation props_BinaryBooleanExpression;
  private ConceptPresentation props_BinaryComparason;
  private ConceptPresentation props_BinaryConnection;
  private ConceptPresentation props_BinaryExpression;
  private ConceptPresentation props_BinaryOperation;
  private ConceptPresentation props_BooleanConstant;
  private ConceptPresentation props_Constant;
  private ConceptPresentation props_DataSetTestCase;
  private ConceptPresentation props_Dataset;
  private ConceptPresentation props_DatasetRef;
  private ConceptPresentation props_Expression;
  private ConceptPresentation props_FloatConstant;
  private ConceptPresentation props_IntegerConstant;
  private ConceptPresentation props_Metric;
  private ConceptPresentation props_MetricRef;
  private ConceptPresentation props_Model;
  private ConceptPresentation props_ModelRef;
  private ConceptPresentation props_NotOperation;
  private ConceptPresentation props_Parameter;
  private ConceptPresentation props_Predicate;
  private ConceptPresentation props_SingleDataTestCase;
  private ConceptPresentation props_SingleValue;
  private ConceptPresentation props_Specification;
  private ConceptPresentation props_TestCase;
  private ConceptPresentation props_TestCaseUsage;
  private ConceptPresentation props_TestWorkbench;
  private ConceptPresentation props_TextLine;
  private ConceptPresentation props_UnaryExpression;
  private ConceptPresentation props_Variable;
  private ConceptPresentation props_VariableReference;
  private ConceptPresentation props_WorkBench;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.Argument:
        if (props_Argument == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Argument");
          props_Argument = cpb.create();
        }
        return props_Argument;
      case LanguageConceptSwitch.BinaryBooleanExpression:
        if (props_BinaryBooleanExpression == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_BinaryBooleanExpression = cpb.create();
        }
        return props_BinaryBooleanExpression;
      case LanguageConceptSwitch.BinaryComparason:
        if (props_BinaryComparason == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("binary comparason");
          props_BinaryComparason = cpb.create();
        }
        return props_BinaryComparason;
      case LanguageConceptSwitch.BinaryConnection:
        if (props_BinaryConnection == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("binary connection");
          props_BinaryConnection = cpb.create();
        }
        return props_BinaryConnection;
      case LanguageConceptSwitch.BinaryExpression:
        if (props_BinaryExpression == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_BinaryExpression = cpb.create();
        }
        return props_BinaryExpression;
      case LanguageConceptSwitch.BinaryOperation:
        if (props_BinaryOperation == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("binary operation");
          props_BinaryOperation = cpb.create();
        }
        return props_BinaryOperation;
      case LanguageConceptSwitch.BooleanConstant:
        if (props_BooleanConstant == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("boolean");
          props_BooleanConstant = cpb.create();
        }
        return props_BooleanConstant;
      case LanguageConceptSwitch.Constant:
        if (props_Constant == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Constant");
          props_Constant = cpb.create();
        }
        return props_Constant;
      case LanguageConceptSwitch.DataSetTestCase:
        if (props_DataSetTestCase == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_DataSetTestCase = cpb.create();
        }
        return props_DataSetTestCase;
      case LanguageConceptSwitch.Dataset:
        if (props_Dataset == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Dataset = cpb.create();
        }
        return props_Dataset;
      case LanguageConceptSwitch.DatasetRef:
        if (props_DatasetRef == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByReference(0x91a99801f144985L, 0xb06a9c8c7ccee4a2L, 0x4c6662695c18d0e0L, 0x4c6662695c18d0e1L, "ref", "", "");
          props_DatasetRef = cpb.create();
        }
        return props_DatasetRef;
      case LanguageConceptSwitch.Expression:
        if (props_Expression == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_Expression = cpb.create();
        }
        return props_Expression;
      case LanguageConceptSwitch.FloatConstant:
        if (props_FloatConstant == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("float");
          props_FloatConstant = cpb.create();
        }
        return props_FloatConstant;
      case LanguageConceptSwitch.IntegerConstant:
        if (props_IntegerConstant == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("integer");
          props_IntegerConstant = cpb.create();
        }
        return props_IntegerConstant;
      case LanguageConceptSwitch.Metric:
        if (props_Metric == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Metric = cpb.create();
        }
        return props_Metric;
      case LanguageConceptSwitch.MetricRef:
        if (props_MetricRef == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("metric call");
          props_MetricRef = cpb.create();
        }
        return props_MetricRef;
      case LanguageConceptSwitch.Model:
        if (props_Model == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Model = cpb.create();
        }
        return props_Model;
      case LanguageConceptSwitch.ModelRef:
        if (props_ModelRef == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByReference(0x91a99801f144985L, 0xb06a9c8c7ccee4a2L, 0x6a7de6ab4eae4a88L, 0x6a7de6ab4eae4a92L, "ref", "", "");
          props_ModelRef = cpb.create();
        }
        return props_ModelRef;
      case LanguageConceptSwitch.NotOperation:
        if (props_NotOperation == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("not");
          props_NotOperation = cpb.create();
        }
        return props_NotOperation;
      case LanguageConceptSwitch.Parameter:
        if (props_Parameter == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Parameter = cpb.create();
        }
        return props_Parameter;
      case LanguageConceptSwitch.Predicate:
        if (props_Predicate == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Predicate");
          props_Predicate = cpb.create();
        }
        return props_Predicate;
      case LanguageConceptSwitch.SingleDataTestCase:
        if (props_SingleDataTestCase == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_SingleDataTestCase = cpb.create();
        }
        return props_SingleDataTestCase;
      case LanguageConceptSwitch.SingleValue:
        if (props_SingleValue == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_SingleValue = cpb.create();
        }
        return props_SingleValue;
      case LanguageConceptSwitch.Specification:
        if (props_Specification == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Specification");
          props_Specification = cpb.create();
        }
        return props_Specification;
      case LanguageConceptSwitch.TestCase:
        if (props_TestCase == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_TestCase = cpb.create();
        }
        return props_TestCase;
      case LanguageConceptSwitch.TestCaseUsage:
        if (props_TestCaseUsage == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("TestCaseUsage");
          props_TestCaseUsage = cpb.create();
        }
        return props_TestCaseUsage;
      case LanguageConceptSwitch.TestWorkbench:
        if (props_TestWorkbench == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_TestWorkbench = cpb.create();
        }
        return props_TestWorkbench;
      case LanguageConceptSwitch.TextLine:
        if (props_TextLine == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("TextLine");
          props_TextLine = cpb.create();
        }
        return props_TextLine;
      case LanguageConceptSwitch.UnaryExpression:
        if (props_UnaryExpression == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_UnaryExpression = cpb.create();
        }
        return props_UnaryExpression;
      case LanguageConceptSwitch.Variable:
        if (props_Variable == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Variable = cpb.create();
        }
        return props_Variable;
      case LanguageConceptSwitch.VariableReference:
        if (props_VariableReference == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByReference(0x91a99801f144985L, 0xb06a9c8c7ccee4a2L, 0x6a7de6ab4ec961f0L, 0x6a7de6ab4ec96ef2L, "ref", "", "");
          props_VariableReference = cpb.create();
        }
        return props_VariableReference;
      case LanguageConceptSwitch.WorkBench:
        if (props_WorkBench == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_WorkBench = cpb.create();
        }
        return props_WorkBench;
    }
    return null;
  }
}
