package DLTL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_DefaultValues extends EnumerationDescriptorBase {

  public EnumerationDescriptor_DefaultValues() {
    super(0x91a99801f144985L, 0xb06a9c8c7ccee4a2L, 0x6a7de6ab4eafefb1L, "DefaultValues", "r:892f7aaa-1f94-4be5-a872-740f44068c69(DLTL.structure)/7673542963543142321");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_EmptyString_0 = new EnumerationDescriptor.MemberDescriptor("EmptyString", "\"\"", 0x6a7de6ab4eafefb3L, "r:892f7aaa-1f94-4be5-a872-740f44068c69(DLTL.structure)/7673542963543142323");
  private final EnumerationDescriptor.MemberDescriptor myMember_Zero_0 = new EnumerationDescriptor.MemberDescriptor("Zero", "0", 0x6a7de6ab4eafefb6L, "r:892f7aaa-1f94-4be5-a872-740f44068c69(DLTL.structure)/7673542963543142326");
  private final EnumerationDescriptor.MemberDescriptor myMember_EmptyList_0 = new EnumerationDescriptor.MemberDescriptor("EmptyList", "[]", 0x6a7de6ab4eafefb2L, "r:892f7aaa-1f94-4be5-a872-740f44068c69(DLTL.structure)/7673542963543142322");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x91a99801f144985L, 0xb06a9c8c7ccee4a2L, 0x6a7de6ab4eafefb1L, 0x6a7de6ab4eafefb3L, 0x6a7de6ab4eafefb6L, 0x6a7de6ab4eafefb2L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_EmptyString_0, myMember_Zero_0, myMember_EmptyList_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_EmptyString_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "EmptyString":
        return myMember_EmptyString_0;
      case "Zero":
        return myMember_Zero_0;
      case "EmptyList":
        return myMember_EmptyList_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
