package DLTL.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int DataSetTestCase = 0;
  public static final int Dataset = 1;
  public static final int Model = 2;
  public static final int ModelReference = 3;
  public static final int Parameter = 4;
  public static final int Predicate = 5;
  public static final int SimpleStatement = 6;
  public static final int SingleDataTestCase = 7;
  public static final int TestCase = 8;
  public static final int TestCaseUsage = 9;
  public static final int TestWorkbench = 10;
  public static final int WorkBench = 11;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x91a99801f144985L, 0xb06a9c8c7ccee4a2L);
    builder.put(0x6a7de6ab4ea9f3ffL, DataSetTestCase);
    builder.put(0x6a7de6ab4eae4a4aL, Dataset);
    builder.put(0x6a7de6ab4ea8cb72L, Model);
    builder.put(0x6a7de6ab4eae4a88L, ModelReference);
    builder.put(0x6a7de6ab4eae4aaaL, Parameter);
    builder.put(0x6a7de6ab4ebf0714L, Predicate);
    builder.put(0x6a7de6ab4eafefacL, SimpleStatement);
    builder.put(0x6a7de6ab4eae4a6dL, SingleDataTestCase);
    builder.put(0x6a7de6ab4ea9d6bbL, TestCase);
    builder.put(0x6a7de6ab4eae4a77L, TestCaseUsage);
    builder.put(0x6a7de6ab4eae4a27L, TestWorkbench);
    builder.put(0x6a7de6ab4ea5b68dL, WorkBench);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
